name: weatherapp_starter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  get: ^4.6.5
  http: ^0.13.4
  intl: ^0.17.0
  sleek_circular_slider: ^2.0.1

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/weather/
